tasks:
  - name: install software
    before: |
      nix profile install nixpkgs#exercism nixpkgs#git-extras
      poetry install

  - name: install software
    init: |
      nix profile install nixpkgs#exercism nixpkgs#git-extras
