name: ballerina

on:
  push:
    paths:
      - 'ballerina/**'
    branches:
      - main
  pull_request:
    paths:
      - 'ballerina/**'

jobs:
  test:
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ballerina-platform/ballerina-action@master
      - run: ballerina test --offline
