name: ballerina

on:
  push:
    paths:
      - 'ballerina/**'
    branches:
      - main
  pull_request:
    paths:
      - 'ballerina/**'

jobs:
  test:
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: changed-dirs
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          files: ballerina
          files_ignore: |
            **/.exercism
            **/tests

      - name: bal test
        id: bal-test
        uses: ballerina-platform/ballerina-action@master
        with:
          args:
            test
        env:
          WORKING_DIR: ${{ steps.changed-dirs.outputs.all_changed_files }}

# bal format always exits zero, so cant exit with error
# right now when a file needs formatting

#   format:
#     runs-on:
#       - ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: changed-dirs
#         id: changed-dirs
#         uses: tj-actions/changed-files@v35
#         with:
#           dir_names: true
#           files: ballerina
#           files_ignore: |
#             **/.exercism
#             **/tests

#       - name: bal format
#         id: bal-format
#         uses: ballerina-platform/ballerina-action@master
#         with:
#           args:
#             format
#         env:
#           WORKING_DIR: ${{ steps.changed-dirs.outputs.all_changed_files }}
