name: ballerina

on:
  push:
    paths:
      - 'ballerina/**'
    branches:
      - main
  pull_request:
    paths:
      - 'ballerina/**'

jobs:
  changed-files:
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: changed-dirs
        id: changed-dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          files: ballerina
          files_ignore: |
            .exercism
            tests
      
      - name: ls-changed-dirs
        id: ls-changed-dirs
        run: ls -ld ${{ steps.changed-dirs.outputs.all_changed_files }}


# jobs:
#   build:
#     runs-on:
#       - ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: ballerina-platform/ballerina-action@master
#         with:
#           args: 
#             build
#         env:
#           WORKING_DIR: ./ballerina/calculator-service

# check into this: https://github.com/marketplace/actions/changed-files#example``s