name: bashchanged-files

on:
  push:
    paths:
      - 'bash/**'
    branches:
      - main
  pull_request:
    paths:
      - 'bash/**'

jobs:
  setup-bats:
    runs-on:
      - ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: changed-files
        id: changed-files
        uses: tj-actions/changed-files@v38.2.1
        with:
          files: *.sh

      - name: bats
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.0
        run: bats -r .
