name: elm

on:
  push:
    paths:
      - 'elm/**'
    branches:
      - main
  pull_request:
    paths:
      - 'elm/**'

jobs:
  format:
    runs-on:
      - ubuntu-20.04
    steps:
      - uses: jorelali/setup-elm@v5
      - run: elm-format --yes src/
