name: elm

on:
  push:
    paths:
      - 'elm/**'
    branches:
      - main
  pull_request:
    paths:
      - 'elm/**'

jobs:
  format:
    runs-on:
      - ubuntu-20.04
    steps:
      - uses: sparksp/elm-format-action@v1
        with:
          elm_files: src/
