name: haskell

on:
  push:
    paths:
      - 'haskell/**'
    branches:
      - main
  pull_request:
    paths:
      - 'haskell/**'

jobs:
  test:
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          fetch-depth: 0
          ghc-version: 9.2.8
      - run: test
      


      # - name: changed-dirs
      #   id: changed-dirs
      #   uses: tj-actions/changed-files@v35
      #   with:
      #     dir_names: true
      #     files: ballerina
      #     files_ignore: |
      #       **/.exercism
      #       **/tests
      
      # - name: haskell test
      #   id: haskell-test
      #   uses: ballerina-platform/ballerina-action@master
      #   with:
      #     args:
      #       test
      #   env:
      #     WORKING_DIR: ${{ steps.changed-dirs.outputs.all_changed_files }}