name: haskell

on:
  push:
    paths:
      - 'haskell/**'
    branches:
      - main
  pull_request:
    paths:
      - 'haskell/**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: changed-dirs
      id: changed-dirs
      uses: tj-actions/changed-files@v35
      with:
        dir_names: true
        files: haskell
        files_ignore: |
          **/.exercism
          **/tests

    - name: test 
      id: test
      uses: haskell/actions/setup@v2
      with:
        ghc-version: 9.2.7
        enable-stack: true
        stack-version: 2.9.1
      env:
        WORKING_DIR: ${{ steps.changed-dirs.outputs.all_changed_files }}
      steps:
        - run: stack test