name: julia

on:
  push:
    paths:
      - 'julia/**'
    branches:
      - main
  pull_request:
    paths:
      - 'julia/**'

jobs:
  formatter:
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1.9.2
        with:
          version: 1.8.5
      - run: |
          julia -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
          julia -e 'using JuliaFormatter; format(".", verbose=true)'

  test:
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1.9.2
        with:
          version: 1.8.5
      - run: |
          julia $(git ls-files '*.jl' | grep runtests.jl)