name: ocaml

on:
  push:
    paths:
      - 'ocaml/**'
    branches:
      - master
  pull_request:
    paths:
      - 'ocaml/**'

jobs:
  ocaml:
    runs-on:
      - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
      - run: opam exec -- dune runtest
