name: pytest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pytest:
    runs-on:
      - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: pytest
              uses: abatilo/actions-poetry@v2.0.0


        
          

